#include <stdio.h>
#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "hardware/i2c.h"
#include "hardware/gpio.h"

#include "sh2.h"
#include "sh2_SensorValue.h"
#include "sh2_err.h"
#include "sh2_pico_hal.h"
#include "hardware/pio.h"
// This header is generated by CMake from the .pio file
#include "quadrature_encoder.pio.h"

// -------------------- Hardware Definitions --------------------
#define PIN_RST 10
#define PIN_INT 11
#define I2C_INST i2c1

// Encoder Pins (Using GPIO 14 and 15 for Phase A/B)
#define PIN_ENCODER_A 14
#define PIN_ENCODER_B 15

// -------------------- Sweep Parameter Definitions --------------------
uint32_t sweep_freqs[] = {50, 100, 200, 400}; 
#define FREQ_COUNT (sizeof(sweep_freqs) / sizeof(sweep_freqs[0]))
#define SAMPLES_PER_TEST 500

// --- PIO Definitions ---
PIO pio = pio0;
uint sm = 0;

// -------------------- Global State Variables --------------------
volatile int32_t jitter_array[SAMPLES_PER_TEST];
volatile int32_t encoder_pos_array[SAMPLES_PER_TEST]; // Store encoder pos alongside jitter
volatile int32_t global_encoder_count = 0; 
volatile uint32_t current_idx = 0;
volatile bool recording_enabled = false;
volatile uint32_t current_target_period_us = 10000; 
volatile bool config_update_requested = false;     

// -------------------- Global Flags --------------------
volatile bool data_ready_flag = false;
volatile uint32_t last_arrival_time_us = 0;

// -------------------- Interrupt Service Routine (ISR) --------------------
void gpio_callback(uint gpio, uint32_t events) {
    // Handle IMU Interrupt
    if (gpio == PIN_INT) {
        data_ready_flag = true; 
    }
}

// -------------------- Sensor Callback --------------------
void sensorHandler(void *cookie, sh2_SensorEvent_t *event)
{
    sh2_SensorValue_t value;
    if (sh2_decodeSensorEvent(&value, event) == SH2_OK)
    {
        if (value.sensorId == SH2_GAME_ROTATION_VECTOR)
        {
            uint32_t now = to_us_since_boot(get_absolute_time());
            
            if (recording_enabled && current_idx < SAMPLES_PER_TEST && last_arrival_time_us != 0) {
                uint32_t dt = now - last_arrival_time_us;
                int32_t jitter = (int32_t)dt - current_target_period_us;
                
                jitter_array[current_idx] = jitter;
                // Drain the FIFO of all pending encoder events and update the count
                while (!pio_sm_is_rx_fifo_empty(pio, sm)) {
                    uint32_t direction = pio_sm_get(pio, sm);
                    if (direction == 0) { // As pushed by the 'forwards' block
                        global_encoder_count++;
                    } else { // As pushed by the 'backwards' block
                        global_encoder_count--;
                    }
                }
                encoder_pos_array[current_idx] = global_encoder_count;
                current_idx++;
            }
            last_arrival_time_us = now;
        }
    }
}

// -------------------- Core1: Sensor Communication --------------------
void core1_entry()
{
    i2c_init(I2C_INST, 400 * 1000); 
    gpio_set_function(6, GPIO_FUNC_I2C);
    gpio_set_function(7, GPIO_FUNC_I2C);
    gpio_pull_up(6);
    gpio_pull_up(7);

    gpio_init(PIN_RST);
    gpio_set_dir(PIN_RST, GPIO_OUT);
    gpio_put(PIN_RST, 0);
    sleep_ms(200);
    gpio_put(PIN_RST, 1);
    sleep_ms(1000);

    // IMU Interrupt Setup
    gpio_init(PIN_INT);
    gpio_set_dir(PIN_INT, GPIO_IN);
    gpio_pull_up(PIN_INT);

    // Setup PIO for the encoder
    uint offset = pio_add_program(pio, &quadrature_encoder_program);
    pio_sm_config c = quadrature_encoder_program_get_default_config(offset);
    sm_config_set_in_pins(&c, PIN_ENCODER_A); // Base pin
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX); // Join FIFOs to make an 8-deep RX FIFO
    sm_config_set_in_shift(&c, false, false, 0); // Shift Left to construct index correctly
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);

    // Only the IMU needs a CPU interrupt now
    gpio_set_irq_enabled_with_callback(PIN_INT, GPIO_IRQ_EDGE_FALL, true, &gpio_callback);

    sh2_Hal_t* hal = get_sh2_pico_hal();
    if (sh2_open(hal, NULL, NULL) != SH2_OK) return;
    sh2_setSensorCallback(sensorHandler, NULL);

    while (true)
    {
        if (config_update_requested) {
            sh2_SensorConfig_t config = {};
            config.reportInterval_us = current_target_period_us;
            sh2_setSensorConfig(SH2_GAME_ROTATION_VECTOR, &config);
            config_update_requested = false; 
        }

        if (data_ready_flag) {
            data_ready_flag = false;
        }
        sh2_service();
        tight_loop_contents();
    }
}

// -------------------- Core0: Logic & Data Analysis --------------------
int main()
{
    stdio_init_all();
    sleep_ms(5000); 

    printf("\n=== BNO085 + ENCODER INTEGRATED TEST ===\n");
    
    multicore_launch_core1(core1_entry);

    for (uint i = 0; i < FREQ_COUNT; i++) {
        uint32_t freq = sweep_freqs[i];
        current_target_period_us = 1000000 / freq;

        printf("\n>>> TESTING FREQUENCY: %d Hz\n", freq);
        
        config_update_requested = true;
        while(config_update_requested) { tight_loop_contents(); } 

        printf("Wait 3s for stabilization...\n");
        sleep_ms(3000);

        current_idx = 0;
        last_arrival_time_us = 0; 
        recording_enabled = true;
        
        printf("Sampling...");
        while (current_idx < SAMPLES_PER_TEST) {
            tight_loop_contents(); 
        }
        recording_enabled = false;
        printf(" Done.\n");

        // Data Dump
        printf("---DATA_START:%dHZ---\n", freq);
        printf("index,jitter_us,encoder_ticks\n");
        
        for (uint32_t j = 0; j < SAMPLES_PER_TEST; j++) {
            printf("%u,%ld,%ld\n", j, jitter_array[j], encoder_pos_array[j]);
        }

        printf("---SUMMARY:%dHZ---\n", freq);
        // Drain any remaining encoder events from the FIFO to get the final count
        while (!pio_sm_is_rx_fifo_empty(pio, sm)) {
            uint32_t direction = pio_sm_get(pio, sm);
            if (direction == 0) {
                global_encoder_count++;
            } else {
                global_encoder_count--;
            }
        }
        printf("Final Encoder Count: %ld\n", global_encoder_count);
        printf("---DATA_END---\n");

        sleep_ms(1000); 
    }

    printf("\n=== ALL TESTS COMPLETE ===\n");
    while (true) { tight_loop_contents(); }
}